config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#show'
  get 'pages/show'
  post 'pages/show', to: 'pages#update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sketches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    has_one_attached :image
end

app/models/sketch.rb
class Sketch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  # def index
  #   @pages = Page.all
  # end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @width ||= 800
    @height ||= 600
    # @page = Page.new
  end

  # def image
  #     @page = @page.image.attach(params[:image])
  # end

  # GET /pages/new
  # def new
  #   @page = Page.new
  # end

  # GET /pages/1/edit
  # def edit
  # end

  # POST /pages
  # POST /pages.json
  # def create
  #   @page = Page.new(page_params)
  #
  #   respond_to do |format|
  #     if @page.save
  #       format.html { redirect_to @page, notice: 'Page was successfully created.' }
  #       format.json { render :show, status: :created, location: @page }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @page.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end



  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
     @size = params[:resolution]
     case @size[:res_string]
     when "640x480"
       @width = 640
       @height = 480
     when "800x600"
       @width = 800
       @height = 600
     when "1024x768"
       @width = 1024
       @height = 768
     end
     render :show
   end

  # DELETE /pages/1
  # DELETE /pages/1.json
  # def destroy
  #   @page.destroy
  #   respond_to do |format|
  #     format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # private
    # Use callbacks to share common setup or constraints between actions.
    # def set_page
    #   @page = Page.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    # def page_params
    #   params.require(:page).permit(:title, :content, :image)
    # end
end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController
  before_action :set_sketch, only: [:show, :edit, :update, :destroy]

  # GET /sketches
  # GET /sketches.json
  def index
    @sketches = Sketch.all
  end

  # GET /sketches/1
  # GET /sketches/1.json
  def show
  end

  # GET /sketches/new
  def new
    @sketch = Sketch.new
  end

  # GET /sketches/1/edit
  def edit
  end

  # POST /sketches
  # POST /sketches.json
  def create
    @sketch = Sketch.new(sketch_params)
    @sketch.code = @sketch.code.strip
    respond_to do |format|
      if @sketch.save
        format.html { redirect_to @sketch, notice: 'Sketch was successfully created.' }
        format.json { render :show, status: :created, location: @sketch }
      else
        render :new
        # format.json { render json: @sketch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sketches/1
  # PATCH/PUT /sketches/1.json
  def update
    respond_to do |format|
      if @sketch.update(sketch_params)
        format.html { redirect_to @sketch, notice: 'Sketch was successfully updated.' }
        format.json { render :show, status: :ok, location: @sketch }
      else
        format.html { render :edit }
        format.json { render json: @sketch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sketches/1
  # DELETE /sketches/1.json
  def destroy
    @sketch.destroy
    respond_to do |format|
      format.html { redirect_to sketches_url, notice: 'Sketch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sketch
      @sketch = Sketch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sketch_params
      params.require(:sketch).permit(:artist, :description, :code)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        render json: { status: 200, message: "StyleShare App"}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StyleShareFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.14.0/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.14.0/firebase-analytics.js"></script>
  </head>

  <body>
      <section id="navbar">
      <div class="navbar-top">
        <div class="navbar area">
           <h1><%= link_to "StyleShare", sketches_path %></h1>
        </div>
        <div class="navbar-links" id="navigation">
          <ul>
            <li><%= link_to "User Sketches!", root_path %></li>
          </ul>
          <button data-collapse data-target="#navigation" class="toggle" <span class="icon"></span></button>
        </div>
      </div>
    </section>

    <section class="main-container">
        <%= yield %>
    </section>

  </body>
</html>

app/views/pages/_canvas_model.html.erb
<div class="center-div">

    <h2>Enter Your Prompt Pic:</h2>

    <div class="sketch-form">
    <%= form_for :resolution, url: pages_show_path do |form| %>
    <%= form.file_field :image %>
    <%# <%= render :partial => 'prompts/form' %>
    <% end %>
    </div>


    <h2>Your Canvas</h2>

    <%= form_for :resolution, url: pages_show_path do |f| %>
    <%= f.select :res_string, options_for_select([["1024x768"],["800x600"],["640x480"]]) %>
    <%= f.submit "Change" %>
    <% end %>

    <p id="canvas-size"></p>
    <div id="p5canvas">
    </div>
    <p>
        <button id="saveButton">save sketch</button>
        <button id="clearButton">clear</button>
    </p>
</div>

<%= render 'user_canvas' %>

    <p>
        <ol id="sketchlist">

        </ol>

app/views/pages/_user_canvas.html.erb
<script>
    var database;

    sketch = [];
    currentPath = [];
    begin = false;


    function setup(){
        let canvas = createCanvas(<%= @width %>,<%= @height %>).parent("#p5canvas");
        $("#canvas-size").text(width + "x" + height);

        canvas.mousePressed(startPath);
        canvas.mouseReleased(endPath);

        var saveButton = select('#saveButton');
        saveButton.mousePressed(saveSketch);

        var clearButton = select('#clearButton');
        clearButton.mousePressed(clearSketch);

        var firebaseConfig = {
            apiKey: "AIzaSyAdx29D2inic1dpeMBLybWE-eFj8gFH6QU",
            authDomain: "style-share-app.firebaseapp.com",
            databaseURL: "https://style-share-app.firebaseio.com",
            projectId: "style-share-app",
            storageBucket: "style-share-app.appspot.com",
            messagingSenderId: "98876833458",
            appId: "1:98876833458:web:40d7dccd6f25d88e8193ab",
            measurementId: "G-KESFNKEWBJ"
        };
        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
        firebase.analytics();
        database = firebase.database();

        var params = getURLParams();
        console.log(params);
        if(params.id) {
            console.log(params.id);
            showSketch(params.id);
        }

        var ref = database.ref('sketches');
        ref.on('value', gotData, errData);
    }

    function startPath() {
        begin = true;
        currentPath = [];
        sketch.push(currentPath);
    }

    function endPath() {
        begin = false;
    }

    function draw() {
        background(255,255,255);

        if(begin){
            var point = {
                x: mouseX,
                y: mouseY
            };
            currentPath.push(point);
        }

    stroke(0,0,0);
    noFill();
    for (var i = 0; i < sketch.length; i++) {
        var path = sketch[i];
        beginShape();
        for(var m = 0; m < path.length; m++){
            vertex(path[m].x, path[m].y);
        }
        endShape();
        }
    }

    function saveSketch() {
        var ref = database.ref('sketches')
        var data = {
            name: "Will",
            sketch: sketch
        };
        var result = ref.push(data, dataSent);
        console.log(result.key);

        function dataSent(err, status) {
            console.log(status);
        }
    }
        function gotData(data) {
            var showcase = selectAll('listing');
            for(var i = 0; i < showcase.length; i++) {
                showcase[i].remove();
            }

            var sketches = data.val();
            var keys = Object.keys(sketches);
            for (var j = 0; j < keys.length; j++) {
                var key = keys[j];
                var li = createElement('li', '');
                li.class('listing');
                var ahref = createA('#', key);
                ahref.mousePressed(showSketch);
                ahref.parent(li);

                var perma = createA('?id=' + key, 'project link');
                perma.parent(li);
                perma.style('padding', '4px');

                li.parent('sketchlist');
            }
        }

        function errData(err) {
            console.log(err);
        }

        function showSketch(key) {
            if (key instanceof MouseEvent) {
                key = this.html();
            }
            var ref = database.ref('sketches/' + key);
            ref.once('value', oneSketch, errData);

            function oneSketch(data) {
                var dbsketch = data.val();
                sketch = dbsketch.sketch;
            }
        }

        function clearSketch() {
            sketch = [];
        }

</script>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<%= render 'canvas_model' %>

app/views/sketches/_form.html.erb
<%= form_with(model: sketch, local: true) do |form| %>
  <% if sketch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sketch.errors.count, "error") %> prohibited this sketch from being saved:</h2>

      <ul>
        <% sketch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_area :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sketches/_sketch.html.erb
<div class="rounded-box inline">
    <div class="sketch-info">
        <ul>
            <li>
                <p class="sketch-artist"><%= sketch.artist %></p>
            </li>
            <li>
                <p>Description:</p>
                <small><%= sketch.description %></small>
            </li>
        </ul>
    </div>
    <br>
    <div class="links-bottom">
        <small><%= link_to "Open", sketch %></small>
        <small><%= link_to "Edit", edit_sketch_path(sketch) %></small>
        <small><%= link_to "Delete", sketch, method: :delete %></small>
    </div>
</div>

app/views/sketches/edit.html.erb
<div class="container">
    <h1>Editing Sketch</h1>

    <%= render 'form', sketch: @sketch %>
</div>
<%= link_to 'Show', @sketch %> |
<%= link_to 'Back', sketches_path %>

app/views/sketches/index.html.erb
<div class="container">

<h1>StyleShare User Showcase</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Description</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sketches.each do |sketch| %>
      <tr>
        <td><%= sketch.artist %></td>
        <td><%= sketch.description %></td>
        <td><%= sketch.code %></td>
        <td><%= link_to 'Show', sketch %></td>
        <td><%= link_to 'Edit', edit_sketch_path(sketch) %></td>
        <td><%= link_to 'Destroy', sketch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
    <div class="main-link">
        <%= link_to 'New Sketch', new_sketch_path %>
    </div>

</div>

app/views/sketches/new.html.erb
<div class="center-div">
    <h1>New Sketch</h1>

    <div class="form-container">
        <%= render 'form', sketch: @sketch %>
    </div>

</div>


<%= link_to 'Back', sketches_path %>

app/views/sketches/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @sketch.artist %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sketch.description %>
</p>

<p>
  <strong>Code:</strong>
  <%= @sketch.code %>
</p>

<%= link_to 'Edit', edit_sketch_path(@sketch) %> |
<%= link_to 'Back', sketches_path %>

</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
    The time is now: <%= Time.now %>
</p>